AWSTemplateFormatVersion: '2010-09-09'
Description: Some storage with input and output

Parameters:
  ProjectName:
    Type: String
    Description: Nome dell'ambiente destinazione

  # Unused but required by CD pipeline
  MicroserviceNumber:
    Type: Number
    Description: An unique number that identify the microservice inside the ECS cluster.

  # Unused but required by CD pipeline
  TemplateBucketBaseUrl:
    Type: String
    Description: URL da cui caricare i frammenti di template di infrastruttura
  
  Version:
    Type: String
    Description: 'keep track of used projects commitIds'
  
  # CdcKinesisSourceStreamArn:
  #   Type: String
  #   Description: 'Where to send CDC'


Resources:

  PnSmTableClientStates:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: 'pn-SmStates'
      AttributeDefinitions:
        - AttributeName: 'processClientId'
          AttributeType: 'S'
        - AttributeName: 'currStatus'
          AttributeType: 'S'
      KeySchema: 
        - AttributeName: 'processClientId'
          KeyType: 'HASH'
        - AttributeName: 'currStatus'
          KeyType: 'RANGE'
      #KinesisStreamSpecification:
      #  StreamArn: 'String'
      BillingMode: 'PAY_PER_REQUEST'
      SSESpecification:
        SSEEnabled: true
        SSEType: 'KMS'
      TableClass: 'STANDARD'
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain

Outputs:

  PnSmTableNameClientStates:
    Description: 'Nome della Tabella DynamoDB relativa alla Macchina a Stati'
    Value: !Ref PnSmTableClientStates

  PnSmTableArnClientStates:
    Description: 'ARN della Tabella DynamoDB relativa alla Macchina a Stati'
    Value: !GetAtt PnSmTableClientStates.Arn

