AWSTemplateFormatVersion: '2010-09-09'
Description: Some storage with input and output

Parameters:
  ProjectName:
    Type: String
    Description: Nome dell'ambiente destinazione

  # Unused but required by CD pipeline
  MicroserviceNumber:
    Type: Number
    Description: An unique number that identify the microservice inside the ECS cluster.

  # Unused but required by CD pipeline
  TemplateBucketBaseUrl:
    Type: String
    Description: URL da cui caricare i frammenti di template di infrastruttura
  
  Version:
    Type: String
    Description: 'keep track of used projects commitIds'
  
  # CdcKinesisSourceStreamArn:
  #   Type: String
  #   Description: 'Where to send CDC'


Resources:

  PnSmTableClientStates:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: 'processClientId'
          AttributeType: 'S'
        - AttributeName: 'currStatus'
          AttributeType: 'S'
      KeySchema: 
        - AttributeName: 'processClientId'
          KeyType: 'HASH'
        - AttributeName: 'currStatus'
          KeyType: 'RANGE'
      #KinesisStreamSpecification:
      #  StreamArn: 'String'
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      SSESpecification:
        SSEEnabled: true
        SSEType: 'KMS'
      TableClass: 'STANDARD'
    DeletionPolicy: Retain

  PnSmUploadBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: Private
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  PnSmUploadBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref PnSmUploadBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 's3:*'
            Effect: Allow
            Resource:
              - !GetAtt PnSmUploadBucket.Arn
              - !Join 
                - ''
                - - !GetAtt PnSmUploadBucket.Arn
                  - '/*'
            Principal:
              AWS:
                - !Sub 'arn:aws:iam::${AWS::AccountId}:user/mario.ottone@dgsspa.com'


Outputs:

  PnSmTableNameClientStates:
    Description: 'Nome della Tabella DynamoDB relativa alla Macchina a Stati'
    Value: !Ref PnSmTableClientStates

  PnSmTableArnClientStates:
    Description: 'ARN della Tabella DynamoDB relativa alla Macchina a Stati'
    Value: !GetAtt PnSmTableClientStates.Arn

